### PR TITLE
Test for adding new plant to database via POST request

### PR DESCRIPTION
**Pull request by petmetic**
Added test for resolving a received `post request` via API.

### CODE REVIEW

**Review by jurecuhalev — CHANGES_REQUESTED** [review]
- title and description don't tell me what part of API you're testing
- your tests are failing (because you don't have media in git - you probably should have a small 10x10png in tests folder)
- PR says it's about tests, but you're also refactoring urls - explain why you're doing this

**Review by simonfabcic — COMMENTED** [review]
LGTM

**Comment by petmetic** [comment]
> * PR says it's about tests, but you're also refactoring urls - explain why you're doing this -> different PR

**Comment by jurecuhalev** [comment]
You still don't explain about what you're doing. What API/components are you testing? 

"Testing API" -> "Adding tests for magic endpoint that converts water into wine. Covering cases where input is orange juice to make sure we return error."

**Comment by petmetic** [comment]
> You still don't explain about what you're doing. What API/components are you testing?
> 
> "Testing API" -> "Adding tests for magic endpoint that converts water into wine. Covering cases where input is orange juice to make sure we return error."

This better? If not, need more precise instruction :/

**Review by jurecuhalev — APPROVED** [review]

**Pull request merged**
